modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="cobblestone"
version="1.0.0-alpha"
displayName="Cobblestone"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator,abajiar"
description="Cobblestone give birth to all things."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.cobblestone]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cobblestone]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration